# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bottlerocket}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brett Goulder", "Carl Woodward"]
  s.date = %q{2010-09-10}
  s.default_executable = %q{bottlerocket}
  s.description = %q{A nifty Sinatra/Mongo based CMS system created by one American and an Aussie with an afro}
  s.email = %q{brett.goulder@gmail.com}
  s.executables = ["bottlerocket"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".bundle/config",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "admin/views/edit.haml",
     "admin/views/entities.haml",
     "admin/views/entity.haml",
     "admin/views/index.haml",
     "admin/views/layout.haml",
     "admin/views/show.haml",
     "admin/views/stylesheets/screen.sass",
     "bin/bottlerocket",
     "bottlerocket.gemspec",
     "lib/bottlerocket.rb",
     "lib/bottlerocket/bottlerocket_admin.rb",
     "lib/bottlerocket/generator.rb",
     "lib/bottlerocket/has_connection.rb",
     "lib/bottlerocket/models/configuration.rb",
     "lib/bottlerocket/models/content_type.rb",
     "lib/bottlerocket/models/content_types.rb",
     "lib/bottlerocket/models/entity.rb",
     "lib/bottlerocket/simple_struct.rb",
     "spec/bottlerocket/bottlerocket_admin_spec.rb",
     "spec/bottlerocket/config_test.yaml",
     "spec/bottlerocket/content_type_test.yaml",
     "spec/bottlerocket/generator_spec.rb",
     "spec/bottlerocket/models/configuration_spec.rb",
     "spec/bottlerocket/models/content_type_spec.rb",
     "spec/bottlerocket/models/content_types_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "template/Gemfile",
     "template/README.markdown",
     "template/bottlerocket.yaml",
     "template/config.ru",
     "template/content_types.yaml",
     "template/site.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/the-perfect-gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A nifty Sinatra/Mongo based CMS system}
  s.test_files = [
    "spec/bottlerocket/bottlerocket_admin_spec.rb",
     "spec/bottlerocket/generator_spec.rb",
     "spec/bottlerocket/models/configuration_spec.rb",
     "spec/bottlerocket/models/content_type_spec.rb",
     "spec/bottlerocket/models/content_types_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<sinatra_more>, [">= 0"])
      s.add_runtime_dependency(%q<rspec>, ["= 1.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra_more>, [">= 0"])
      s.add_dependency(%q<rspec>, ["= 1.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra_more>, [">= 0"])
    s.add_dependency(%q<rspec>, ["= 1.3.0"])
  end
end

