require 'yaml'
require 'activesupport'
require 'mongo'
require 'fileutils'
require File.dirname(__FILE__) + '/lib/simple_struct'
require File.dirname(__FILE__) + '/lib/models/configuration'
require File.dirname(__FILE__) + '/lib/models/content_types'
require File.dirname(__FILE__) + '/lib/models/content_type'
require File.dirname(__FILE__) + '/lib/models/entity'