require 'yaml'
require 'active_support'
require 'mongo'
require 'fileutils'
require File.dirname(__FILE__) + '/bottlerocket/simple_struct'
require File.dirname(__FILE__) + '/bottlerocket/models/configuration'
require File.dirname(__FILE__) + '/bottlerocket/models/content_types'
require File.dirname(__FILE__) + '/bottlerocket/models/content_type'
require File.dirname(__FILE__) + '/bottlerocket/models/entity'
require File.dirname(__FILE__) + '/bottlerocket/generator'
require File.dirname(__FILE__) + '/bottlerocket/bottlerocket_admin'

puts File.dirname(__FILE__) + '/bottlerocket/simple_struct'